package ec.edu.espe.medicbyte.view;

import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author Andres Jonathan J.
 */
public class AppointmentItem extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentItem
     */
    public AppointmentItem() {
        initComponents();
        
        // set icons
        lblDate.setIcon(IconFontSwing.buildIcon(FontAwesome.CALENDAR, 14));
        lblHour.setIcon(IconFontSwing.buildIcon(FontAwesome.CLOCK_O, 14));
        lblLocation.setIcon(IconFontSwing.buildIcon(FontAwesome.MAP_MARKER, 14));
        lblMedicName.setIcon(IconFontSwing.buildIcon(FontAwesome.USER_MD, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel12 = new javax.swing.JPanel();
        lblMedicAvatar = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        lblHourValue = new javax.swing.JLabel();
        lblLocationValue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMedicName = new javax.swing.JLabel();
        lblMedicNameValue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnReschedule1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 7, 0));
        setMaximumSize(new java.awt.Dimension(32767, 85));
        setMinimumSize(new java.awt.Dimension(560, 85));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(560, 85));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel12.setPreferredSize(new java.awt.Dimension(550, 100));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        lblMedicAvatar.setBackground(new java.awt.Color(234, 236, 237));
        lblMedicAvatar.setMaximumSize(new java.awt.Dimension(64, 64));
        lblMedicAvatar.setMinimumSize(new java.awt.Dimension(64, 64));
        lblMedicAvatar.setOpaque(true);
        lblMedicAvatar.setPreferredSize(new java.awt.Dimension(64, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel12.add(lblMedicAvatar, gridBagConstraints);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jPanel15.setOpaque(false);

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(71, 71, 71));
        lblDate.setText("Date:");

        lblHour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHour.setForeground(new java.awt.Color(71, 71, 71));
        lblHour.setText("Hour:");

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(71, 71, 71));
        lblLocation.setText("Location:");

        lblDateValue.setText("-");

        lblHourValue.setText("-");

        lblLocationValue.setText("-");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDateValue)
                .addGap(18, 18, 18)
                .addComponent(lblHour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHourValue)
                .addGap(18, 18, 18)
                .addComponent(lblLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLocationValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDate)
                .addComponent(lblHour)
                .addComponent(lblLocation)
                .addComponent(lblDateValue)
                .addComponent(lblHourValue)
                .addComponent(lblLocationValue))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel14.add(jPanel15, gridBagConstraints);

        jPanel2.setOpaque(false);

        lblMedicName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMedicName.setForeground(new java.awt.Color(71, 71, 71));
        lblMedicName.setText("Medic:");

        lblMedicNameValue.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblMedicName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedicNameValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicName)
                    .addComponent(lblMedicNameValue)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel14.add(jPanel2, gridBagConstraints);

        lblStatus.setBackground(new java.awt.Color(206, 247, 236));
        lblStatus.setForeground(new java.awt.Color(25, 183, 142));
        lblStatus.setText("Pendent");
        lblStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 7, 3, 7));
        lblStatus.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel14.add(lblStatus, gridBagConstraints);

        jPanel16.setAlignmentX(0.0F);
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnReschedule1.setBackground(new java.awt.Color(142, 192, 255));
        btnReschedule1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnReschedule1.setForeground(new java.awt.Color(255, 255, 255));
        btnReschedule1.setText("Reschedule");
        btnReschedule1.setAlignmentX(1.0F);
        btnReschedule1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        btnReschedule1.setBorderPainted(false);
        btnReschedule1.setContentAreaFilled(false);
        btnReschedule1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReschedule1.setFocusPainted(false);
        btnReschedule1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReschedule1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReschedule1.setOpaque(true);
        btnReschedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReschedule1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnReschedule1, java.awt.BorderLayout.CENTER);

        jSeparator3.setBackground(new java.awt.Color(28, 104, 180));
        jSeparator3.setForeground(new java.awt.Color(28, 104, 180));
        jSeparator3.setMinimumSize(new java.awt.Dimension(0, 2));
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel4.add(jSeparator3, java.awt.BorderLayout.PAGE_END);

        jPanel17.add(jPanel4);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnCancel.setBackground(new java.awt.Color(255, 137, 137));
        btnCancel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setAlignmentX(1.0F);
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancel.setOpaque(true);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel, java.awt.BorderLayout.CENTER);

        jSeparator4.setBackground(new java.awt.Color(218, 21, 22));
        jSeparator4.setForeground(new java.awt.Color(218, 21, 22));
        jSeparator4.setMinimumSize(new java.awt.Dimension(0, 2));
        jSeparator4.setOpaque(true);
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel3.add(jSeparator4, java.awt.BorderLayout.PAGE_END);

        jPanel17.add(jPanel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel16.add(jPanel17, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel14.add(jPanel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel12.add(jPanel14, gridBagConstraints);

        add(jPanel12);

        jSeparator1.setVisible(false);
        jSeparator1.setBackground(new java.awt.Color(175, 192, 196));
        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 1));
        jSeparator1.setOpaque(true);
        add(jSeparator1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnReschedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReschedule1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReschedule1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReschedule1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblHourValue;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLocationValue;
    private javax.swing.JLabel lblMedicAvatar;
    private javax.swing.JLabel lblMedicName;
    private javax.swing.JLabel lblMedicNameValue;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
