package ec.edu.espe.medicbyte.view;

import ec.edu.espe.medicbyte.model.Appointment;
import ec.edu.espe.medicbyte.util.StringUtils;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

import static javax.swing.JOptionPane.YES_NO_OPTION;


/**
 *
 * @author Andres Jonathan J.
 */
public class AppointmentItem extends javax.swing.JPanel {
    private Runnable cancelCallback;
    
    /**
     * Creates new form AppointmentItem
     * 
     * @param appointment
     */
    public AppointmentItem(Appointment appointment) {
        initComponents();
        
        // set icons
        lblDate.setIcon(IconFontSwing.buildIcon(FontAwesome.CALENDAR, 14));
        lblHour.setIcon(IconFontSwing.buildIcon(FontAwesome.CLOCK_O, 14));
        lblLocation.setIcon(IconFontSwing.buildIcon(FontAwesome.MAP_MARKER, 14));
        lblMedicName.setIcon(IconFontSwing.buildIcon(FontAwesome.USER_MD, 14));
        
        // set values
        lblDateValue.setText(appointment.getDate().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
        
        if (appointment.getMedic() != null) {
            lblMedicNameValue.setText(appointment.getMedic().getProfile().getFullName());
        }
        
        if (appointment.getHour() != null) {
            lblHourValue.setText(appointment.getHour().format(DateTimeFormatter.ofPattern("HH:mm")));
        }
        
        if (appointment.getLocation() != null) {
            lblLocationValue.setText(StringUtils.truncate(appointment.getLocation().getName(), 90));
            lblLocationValue.setToolTipText(appointment.getLocation().getName());
        }
        
        lblSpecialityValue.setText(appointment.getSpeciality().getName());
        
        btnCancel.setVisible(false);
        
        switch (appointment.getStatus().name()) {
            case "PENDENT":
                lblStatus.setBackground(new Color(208, 212, 215));
                lblStatus.setForeground(new Color(149, 160, 161));
                lblStatus.setText("Pendent");
                btnCancel.setVisible(true);
            break;
            case "APPROVED":
                lblStatus.setBackground(new Color(171, 255, 185));
                lblStatus.setForeground(new Color(75, 184, 93));
                lblStatus.setText("Approved");
                btnCancel.setVisible(true);
            break;
            case "RESCHEDULED":
                lblStatus.setBackground(new Color(189, 211, 255));
                lblStatus.setForeground(new Color(30, 144, 255));
                lblStatus.setText("Rescheduled");
            break;
            case "CANCELLED":
                lblStatus.setBackground(new Color(255, 153, 168));
                lblStatus.setForeground(new Color(209, 0, 31));
                lblStatus.setText("Cancelled");
            break;
            case "FINISHED":
                lblStatus.setBackground(new Color(206, 247, 236));
                lblStatus.setForeground(new Color(25, 183, 142));
                lblStatus.setText("Finished");
            break;
            case "REJECTED":
                lblStatus.setBackground(new Color(255, 153, 168));
                lblStatus.setForeground(new Color(209, 0, 31));
                lblStatus.setText("Rejected");
            break;
        }
        
        btnReschedule.setVisible(false);
        lblMedicAvatar.setIcon(IconFontSwing.buildIcon(FontAwesome.USER_MD, 56, new Color(115, 115, 115)));
    }
    
    public void onCancel(Runnable callback) {
        cancelCallback = callback;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblMedicAvatar = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        lblHourValue = new javax.swing.JLabel();
        lblLocationValue = new javax.swing.JLabel();
        pnlInfo2 = new javax.swing.JPanel();
        lblMedicName = new javax.swing.JLabel();
        lblMedicNameValue = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        lblSpecialityValue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnReschedule = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        setMaximumSize(new java.awt.Dimension(32767, 95));
        setMinimumSize(new java.awt.Dimension(560, 95));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(560, 95));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 216, 216), 1, true));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 7, 8, 7));
        jPanel12.setPreferredSize(new java.awt.Dimension(550, 100));
        jPanel12.setLayout(new java.awt.GridBagLayout());

        lblMedicAvatar.setBackground(new java.awt.Color(234, 236, 237));
        lblMedicAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicAvatar.setMaximumSize(new java.awt.Dimension(64, 64));
        lblMedicAvatar.setMinimumSize(new java.awt.Dimension(64, 64));
        lblMedicAvatar.setOpaque(true);
        lblMedicAvatar.setPreferredSize(new java.awt.Dimension(64, 64));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        jPanel12.add(lblMedicAvatar, gridBagConstraints);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridBagLayout());

        jPanel15.setOpaque(false);

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(71, 71, 71));
        lblDate.setText("Date:");

        lblHour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHour.setForeground(new java.awt.Color(71, 71, 71));
        lblHour.setText("Hour:");

        lblLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(71, 71, 71));
        lblLocation.setText("Location:");

        lblDateValue.setText("-");

        lblHourValue.setText("-");

        lblLocationValue.setText("-");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDateValue)
                .addGap(18, 18, 18)
                .addComponent(lblHour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHourValue)
                .addGap(18, 18, 18)
                .addComponent(lblLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLocationValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDate)
                .addComponent(lblHour)
                .addComponent(lblLocation)
                .addComponent(lblDateValue)
                .addComponent(lblHourValue)
                .addComponent(lblLocationValue))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel14.add(jPanel15, gridBagConstraints);

        pnlInfo2.setOpaque(false);

        lblMedicName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMedicName.setForeground(new java.awt.Color(71, 71, 71));
        lblMedicName.setText("Medic:");

        lblMedicNameValue.setText("-");

        lblSpeciality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSpeciality.setText("Speciality:");

        lblSpecialityValue.setText("-");

        javax.swing.GroupLayout pnlInfo2Layout = new javax.swing.GroupLayout(pnlInfo2);
        pnlInfo2.setLayout(pnlInfo2Layout);
        pnlInfo2Layout.setHorizontalGroup(
            pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfo2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblMedicName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMedicNameValue)
                .addGap(12, 12, 12)
                .addComponent(lblSpeciality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSpecialityValue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInfo2Layout.setVerticalGroup(
            pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInfo2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlInfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicName)
                    .addComponent(lblMedicNameValue)
                    .addComponent(lblSpeciality)
                    .addComponent(lblSpecialityValue)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 0, 0);
        jPanel14.add(pnlInfo2, gridBagConstraints);

        lblStatus.setBackground(new java.awt.Color(208, 212, 215));
        lblStatus.setForeground(new java.awt.Color(149, 160, 161));
        lblStatus.setText("Pendent");
        lblStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 7, 3, 7));
        lblStatus.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel14.add(lblStatus, gridBagConstraints);

        jPanel16.setAlignmentX(0.0F);
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridBagLayout());

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnReschedule.setBackground(new java.awt.Color(142, 192, 255));
        btnReschedule.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnReschedule.setForeground(new java.awt.Color(255, 255, 255));
        btnReschedule.setText("Reschedule");
        btnReschedule.setAlignmentX(1.0F);
        btnReschedule.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        btnReschedule.setBorderPainted(false);
        btnReschedule.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReschedule.setFocusPainted(false);
        btnReschedule.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnReschedule.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReschedule.setOpaque(true);
        btnReschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRescheduleActionPerformed(evt);
            }
        });
        jPanel4.add(btnReschedule, java.awt.BorderLayout.CENTER);

        jSeparator3.setBackground(new java.awt.Color(34, 127, 220));
        jSeparator3.setForeground(new java.awt.Color(28, 104, 180));
        jSeparator3.setMinimumSize(new java.awt.Dimension(0, 2));
        jSeparator3.setOpaque(true);
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel4.add(jSeparator3, java.awt.BorderLayout.PAGE_END);

        jPanel17.add(jPanel4);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout());

        btnCancel.setBackground(new java.awt.Color(255, 137, 137));
        btnCancel.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setAlignmentX(1.0F);
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 7, 4, 5));
        btnCancel.setBorderPainted(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setFocusPainted(false);
        btnCancel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancel.setOpaque(true);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel, java.awt.BorderLayout.CENTER);

        jSeparator4.setBackground(new java.awt.Color(218, 21, 22));
        jSeparator4.setForeground(new java.awt.Color(218, 21, 22));
        jSeparator4.setMinimumSize(new java.awt.Dimension(0, 2));
        jSeparator4.setOpaque(true);
        jSeparator4.setPreferredSize(new java.awt.Dimension(0, 2));
        jPanel3.add(jSeparator4, java.awt.BorderLayout.PAGE_END);

        jPanel17.add(jPanel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel16.add(jPanel17, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel14.add(jPanel16, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel12.add(jPanel14, gridBagConstraints);

        jPanel1.add(jPanel12, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jSeparator1.setVisible(false);
        jSeparator1.setBackground(new java.awt.Color(175, 192, 196));
        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 1));
        jSeparator1.setOpaque(true);
        add(jSeparator1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRescheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRescheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRescheduleActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int action = JOptionPane.showConfirmDialog(
            this.getRootPane(),
            "Do you want cancel this appointment?",
            "Are you sure?",
            YES_NO_OPTION
        );
        
        if (action == 0) {
            cancelCallback.run();
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnReschedule;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblHourValue;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLocationValue;
    private javax.swing.JLabel lblMedicAvatar;
    private javax.swing.JLabel lblMedicName;
    private javax.swing.JLabel lblMedicNameValue;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JLabel lblSpecialityValue;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlInfo2;
    // End of variables declaration//GEN-END:variables
}
