package ec.edu.espe.medicbyte.view;

import ec.edu.espe.medicbyte.common.core.View;
import ec.edu.espe.medicbyte.model.Patient;
import ec.edu.espe.medicbyte.model.User;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author Andres Jonathan J.
 */
public class FrmPatients extends View {
    private List<Patient> patients;
    private User currentUser;
    
    /**
     * Creates new form FrmPatients
     */
    public FrmPatients() {
        initComponents();
        setupComponents();
    }
    
    @Override
    protected void onChange(String name, Object oldValue, Object newValue) {
        if (name.equals("patients")) {
            patients = (List<Patient>) newValue;
            patients.sort(Comparator.comparingInt(Patient::getId).reversed());
            updatePatientsList(patients);
        }
        
        if (name.equals("currentUser")) {
            currentUser = (User) newValue;
        }
    }

    @Override
    protected void onLeave() {}

    @Override
    protected void onEnter() {}
    
    private void updatePatientsList(List<Patient> patients) {
        patientsContainer.removeAll();
        
        patients.sort(Comparator.comparingInt(Patient::getId));
        patients.forEach(patient -> {
            PatientListItem item = new PatientListItem(patient, currentUser);
            patientsContainer.add(item);
        });
        
        lblTotalItems.setText(String.valueOf(patients.size()));
        
        repaint();
        revalidate();
    }
    
    private void setupComponents() {
        patientsScrollPanel.getVerticalScrollBar().setUnitIncrement(16);
        patientsScrollPanel.getViewport().setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalItems = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        patientsWrapperPanel = new javax.swing.JPanel();
        patientsScrollPanel = new javax.swing.JScrollPane();
        patientsContainer = new javax.swing.JPanel();
        paginationPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setText("Patients");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setOpaque(false);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Showing");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel3);

        lblTotalItems.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalItems.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotalItems.setText("0");
        lblTotalItems.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        lblTotalItems.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(lblTotalItems);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("result(s)");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel7);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanel3.add(jPanel7);

        patientsWrapperPanel.setBackground(new java.awt.Color(204, 204, 255));
        patientsWrapperPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        patientsWrapperPanel.setOpaque(false);
        patientsWrapperPanel.setLayout(new java.awt.BorderLayout());

        patientsScrollPanel.setBackground(new java.awt.Color(204, 204, 255));
        patientsScrollPanel.setBorder(null);
        patientsScrollPanel.setOpaque(false);

        patientsContainer.setBackground(new java.awt.Color(204, 204, 255));
        patientsContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 8));
        patientsContainer.setOpaque(false);
        patientsContainer.setLayout(new javax.swing.BoxLayout(patientsContainer, javax.swing.BoxLayout.Y_AXIS));
        patientsScrollPanel.setViewportView(patientsContainer);

        patientsWrapperPanel.add(patientsScrollPanel, java.awt.BorderLayout.CENTER);

        jPanel3.add(patientsWrapperPanel);

        paginationPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        paginationPanel.setMaximumSize(new java.awt.Dimension(2147483647, 28));
        paginationPanel.setOpaque(false);
        paginationPanel.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("1");
        paginationPanel.add(jLabel4, java.awt.BorderLayout.CENTER);

        jLabel5.setText("Page:");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 5));
        paginationPanel.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jPanel3.add(paginationPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE_TRAILING;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTotalItems;
    private javax.swing.JPanel paginationPanel;
    private javax.swing.JPanel patientsContainer;
    private javax.swing.JScrollPane patientsScrollPanel;
    private javax.swing.JPanel patientsWrapperPanel;
    // End of variables declaration//GEN-END:variables
}
