package ec.edu.espe.medicbyte.view;

import ec.edu.espe.medicbyte.common.core.View;
import java.awt.Color;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author Andres Jonathan J.
 */
public class PnlLoadingOverlay extends View {
    /**
     * Creates new form PnlLoading
     */
    public PnlLoadingOverlay() {
        initComponents();
        setupComponents();
    }
    
    @Override
    protected void onChange(String name, Object oldValue, Object newValue) {}

    @Override
    protected void onLeave() {}

    @Override
    protected void onEnter() {}
    
    private void setupComponents() {
        lblLoadingMessage.setIconTextGap(10);
        lblLoadingMessage.setIcon(IconFontSwing.buildIcon(FontAwesome.SPINNER, 18, new Color(90, 90, 90)));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoadingMessage = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        lblLoadingMessage.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblLoadingMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("ec/edu/espe/medicbyte/view/Bundle"); // NOI18N
        lblLoadingMessage.setText(bundle.getString("PnlLoadingOverlay.lblLoadingMessage.text")); // NOI18N
        add(lblLoadingMessage, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLoadingMessage;
    // End of variables declaration//GEN-END:variables

}
